name: Закрытие PR в master

on:
  pull_request_target:
    types: [ opened, ready_for_review ]

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{(github.head_ref == 'master' || github.head_ref == 'main' || github.head_ref == 'develop' || github.head_ref == 'stable' || github.head_ref == 'staging')
        && github.event.pull_request.head.repo.fork}}

    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Благодарим за ваш вклад! Похоже, вы создали pull request из ветки master или другой основной ветки разработки. Этого [следует избегать](https://jmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/), поэтому данный pull request был автоматически закрыт. \n \n Мы рекомендуем ознакомиться с [нашей документацией по использованию git](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html). \n \n Вы можете переместить текущую работу в другую ветку, следуя [этим командам](https://ohshitgit.com/#accidental-commit-master). После этого вы можете создать новый pull request, используя нужную ветку."

    # Если вы предпочитаете просто оставить комментарий и не закрывать PR, раскомментируйте код ниже и закомментируйте код выше

    # - uses: actions/github-script@v7
    #   with:
    #     script: |
    #       github.rest.issues.createComment({
    #         issue_number: ${{ github.event.number }},
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: "Благодарим за ваш вклад! Похоже, вы создали pull request из ветки master или другой основной ветки разработки. Этого [следует избегать](https://jmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)\n\nВы можете переместить текущую работу в другую ветку, следуя [этим командам](https://ohshitgit.com/#accidental-commit-master). После этого вы можете создать новый pull request, используя нужную ветку. \n\n Этот pull request не будет закрыт автоматически. Однако мейнтейнер может закрыть его по этой причине."})
