name: "Метки: Одобрено"
on:
  pull_request_review:
    types: [submitted]
jobs:
  add_label:
    # Измените название репозитория после того, как убедитесь, что название команды верно для вашего форка!
    if: ${{ (github.repository == 'Starry-pole/starry-pole-14') && (github.event.review.state == 'APPROVED') }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: tspascoal/get-user-teams-membership@v3
      id: checkUserMember
      with:
        username: ${{ github.actor }}
        team: "content-maintainers,junior-maintainers"
        GITHUB_TOKEN: ${{ secrets.LABELER_PAT }}
    - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: Одобрено"
