name: Проверка конфликтов слияния

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  Label:
    if: ( github.event.pull_request.draft == false ) && ( github.actor != 'PJBot' )
    runs-on: ubuntu-latest
    steps:
      - name: Проверка на наличие конфликтов слияния
        uses: eps1lon/actions-label-merge-conflict@v3.0.0
        with:
          dirtyLabel: "S: Конфликт слияния"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "Этот pull request имеет конфликты, пожалуйста, разрешите их, прежде чем мы сможем оценить pull request."
